version: '3.8'

networks:
  weather-net:
    driver: bridge

volumes:
  namenode-data:
  datanode-data:

services:
  zookeeper:
    image: bitnamilegacy/zookeeper:3.9.2
    container_name: zookeeper
    networks:
      - weather-net
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnamilegacy/kafka:3.7.0
    container_name: kafka
    networks:
      - weather-net
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    networks:
      - weather-net
    ports:
      - "9870:9870"
      - "8020:8020"
    environment:
      - CLUSTER_NAME=weather_cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - namenode-data:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    networks:
      - weather-net
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - datanode-data:/hadoop/dfs/data
    depends_on:
      - namenode

  spark-master:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark-master
    networks:
      - weather-net
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark-worker
    networks:
      - weather-net
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master