apiVersion: v1
kind: Secret
metadata:
  name: climate-secrets
  namespace: climate-monitoring
type: Opaque
stringData:
  OWM_API_KEY: "replace-me"
  AQICN_API_KEY: "replace-me"
  IQAIR_API_KEY: "replace-me"
  AIRFLOW_ADMIN_USERNAME: "admin"
  AIRFLOW_ADMIN_PASSWORD: "admin"
  AIRFLOW_DATABASE_URL: "postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow"
  POSTGRES_USER: "airflow"
  POSTGRES_PASSWORD: "airflow"
  POSTGRES_DB: "airflow"
