apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-init
  namespace: climate-monitoring
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-topic-init
          image: confluentinc/cp-kafka:7.5.0
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - -lc
            - |
              kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic weather.raw.stream --partitions 3 --replication-factor 1
              kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic weather.raw.dlq --partitions 3 --replication-factor 1
              kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic air_quality.raw.stream --partitions 3 --replication-factor 1
              kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic air_quality.raw.dlq --partitions 3 --replication-factor 1
              kafka-topics --bootstrap-server kafka:9092 --list
